influxdb:
  image: influxdb:latest
  container_name: influxdb
  restart: always
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  user: "1000"
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - influxdb-data:/var/lib/influxdb2
    - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - ./influx-configs:/etc/influxdb2/influx-configs:ro
        
      
# Use the influx cli to set up an influxdb instance. 
influxdb_cli:
  links:
   - influxdb
  image: influxdb:latest
  container_name: influxdb_cli
# entrypoint: influx setup --bucket <bucket> -t <token> -o <org> --username=<username> --password=<pass> --host=http://influxdb:8086 -f
# Wait for the influxd service in the influxdb container has fully boostrapped before trying to setup an influxdb instance with the influxdb_cli service. 
  restart: on-failure:10

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  restart: always
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  user: "0"
  links:
    - influxdb
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
    - grafana-data:/var/lib/grafana
